# Nylo - Micro-framework for Flutter.
#
# Website: https://nylo.dev
# Official repository: https://github.com/nylo-core/nylo
# Author: Anthony Gordon <https://github.com/agordn52>

name: flutter_app
description: A new Nylo Flutter application.

publish_to: 'none'

version: 1.0.3+14

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0 <4.0.0"
dependencies:
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  analyzer: ^6.7.0
  intl: ^0.20.2
  nylo_framework: ^6.8.5
  pretty_dio_logger: ^1.4.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.4
  flutter_local_notifications: ^19.1.0
  font_awesome_flutter: ^10.8.0
  scaffold_ui: ^1.2.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  video_player: ^2.9.5
  google_sign_in: ^6.3.0
  cached_network_image: ^3.4.1
  razorpay_flutter: ^1.4.0
  in_app_purchase: ^3.1.13
  chewie: ^1.11.3
  permission_handler: ^12.0.0+1
  media_kit: ^1.2.0
  # ffmpeg_kit_flutter_new: ^1.4.0  # Temporarily disabled due to iOS build issues
  mime: ^2.0.0
  flutter_background_service: ^5.1.0
  flutter_background_service_android: ^6.3.0
  dio: ^5.8.0+1
  flutter_isolate: ^2.1.0

  video_thumbnail: ^0.5.6
  isolate_handler: ^1.0.2
  aws_signature_v4: ^0.6.4
  crypto: ^3.0.6

  connectivity_plus: ^6.1.4
  image_picker: ^1.1.2
  laravel_notify_fcm: ^2.1.0
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_auth: ^5.5.3
  device_info_plus: ^11.3.0
  country_picker: ^2.0.27
  firebase_crashlytics: ^4.3.6
  firebase_analytics: ^11.4.6
  storage_info: ^1.0.0
  flutter_web_auth_2: ^4.1.0
  better_player_plus: ^1.0.8
  webview_flutter: ^4.7.0
  http: ^1.4.0



dev_dependencies:
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.3
  firebase_crashlytics_platform_interface: ^3.6.0
  # The following line 'flutter_lints' activates a set of recommended lints for Flutter apps,
  # packages, and plugins designed to encourage good coding practices.
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# APP ICON - public/app_icon/icon.png
# Build icons: "dart run flutter_launcher_icons"
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "public/images/logo_icon.jpg"
  remove_alpha_ios: true

# RENAME YOUR PROJECT
# flutter pub run rename setAppName --targets ios,android --value "YourAppName"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - public/fonts/
    - public/images/
    - public/app_icon/
    - lang/
    - .env
  fonts:
    - family: Lato
      fonts:
        - asset: public/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: public/fonts/Lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: public/fonts/Lato/Lato-Light.ttf
          weight: 300
        - asset: public/fonts/Lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: public/fonts/Lato/Lato-Regular.ttf
          weight: 400
        - asset: public/fonts/Lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: public/fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: public/fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: public/fonts/Lato/Lato-Black.ttf
          weight: 900
        - asset: public/fonts/Lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic

